CREATE TABLE crm_user(
id INT NOT NULL,
user_name VARCHAR(32) NOT NULL,
user_pwd VARCHAR(32) NOT NULL,
create_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
update_time TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
KEY(id)
)